const express = require('express');
const employee = require('../controllers/employee.controller');
const router = express.Router();
//const validadeUser = require('../validations/user.validation');
const { celebrate, Joi } = require('celebrate');
const authMiddleware = require('../middlewares/auth.middleware');
router.use(authMiddleware);
router.post('/create', employee.create);
router.get('/',employee.index);
router.delete('/delete', employee.delete);
router.put('/update/:id', employee.update);
module.exports = app => app.use('/employee', router);